/**
 * Host-based routing for the five subdomain surfaces.
 *
 * One Next app serves every surface; the Host header picks which one. The
 * middleware resolves the surface + tenant slug (mirroring the backend
 * TenantResolver), rejects unknown hosts, and rewrites public paths to their
 * internal routes:
 *
 *   marketing  web.localhost            `/`            → landing (signup-only)
 *   signup     signup.localhost         `/signup`      → `/signup`
 *   signin     {slug}.signin.localhost  `/signin`      → `/login`
 *   workspace  {slug}.localhost         `/`, `/agents` → `/dashboard/…`
 *   docs       docs.localhost           `/*`           → `/docs/*` (rewrite)
 *
 * Public URLs never contain `/dashboard` or `signin`; the internal
 * `/dashboard/*` tree is the workspace app, served at the tenant root. The
 * docs surface serves the same `/docs/*` tree at the docs hostname root
 * (docs.skyrict.in/getting-started → /docs/getting-started), and `/docs` on
 * the apex marketing host redirects to the canonical docs hostname.
 */

import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

import {
    SESSION_COOKIE,
    baseParts,
    hostSurface,
    signinOrigin,
    signupOrigin,
} from "@/lib/server/auth";

const AUTH_PATHS = [
    "/login",
    "/register",
    "/setup-mfa",
    "/signin",
    "/signup",
    "/invite",
    "/forgot-password",
    "/reset-password",
];

const LEGAL_PATHS = ["/terms", "/privacy"];

const INTERNAL_WORKSPACE_REWRITE_HEADER = "x-internal-workspace-rewrite";

// Framework metadata routes generated at the site root. They have no file
// extension, so the middleware matcher does not skip them, but they are not
// part of the docs tree and must keep serving at the root on the docs surface
// (e.g. the /opengraph-image generated by opengraph-image.tsx).
const DOCS_ROOT_PASSTHROUGH = new Set(["/opengraph-image"]);

function isLegalPath(pathname: string): boolean {
    return LEGAL_PATHS.includes(pathname);
}

function isAuthPath(pathname: string): boolean {
    return (
        AUTH_PATHS.includes(pathname) ||
        pathname.startsWith("/signup/") ||
        pathname.startsWith("/register/") ||
        pathname.startsWith("/mfa/")
    );
}

/**
 * Map a public docs-surface path onto the internal /docs tree. Docs nav links
 * and the Vercel fallback emit /docs-prefixed routes, so those pass through
 * unchanged; everything else is remapped under /docs so the browser URL never
 * exposes the /docs prefix on the docs hostname.
 */
function docsInternalPath(pathname: string): string {
    if (pathname === "/") return "/docs";
    if (pathname.startsWith("/docs")) return pathname;
    return `/docs${pathname}`;
}

function notFound(): NextResponse {
    return NextResponse.rewrite(
        new URL("/_not-found", "http://internal.localhost"),
    );
}

export function middleware(request: NextRequest) {
    const host = request.headers.get("host") ?? "";
    const { surface, slug } = hostSurface(host);
    const { pathname } = request.nextUrl;

    const isApi = pathname.startsWith("/api");
    const isStatic =
        pathname.startsWith("/_next") || pathname === "/favicon.ico";

    if (isStatic) return NextResponse.next();

    if (surface === "unknown") {
        if (isApi)
            return NextResponse.json({ error: "Not found." }, { status: 404 });
        return notFound();
    }

    if (isApi) return NextResponse.next();

    switch (surface) {
        case "marketing": {
            // /docs on the apex host moves to its canonical docs hostname. The
            // redirect is scoped to the apex host so Vercel preview hosts
            // (*.vercel.app) and web.skyrict.in keep serving /docs as the
            // Vercel deployment fallback.
            const hostname = host.replace(/:\d+$/, "").toLowerCase();
            if (
                hostname === "skyrict.in" &&
                (pathname === "/docs" || pathname.startsWith("/docs/"))
            ) {
                const { apex } = baseParts(host);
                const suffix =
                    pathname === "/docs" ? "" : pathname.slice("/docs".length);
                return NextResponse.redirect(
                    new URL(
                        `${request.nextUrl.protocol}//docs.${apex}${suffix}${request.nextUrl.search || ""}`,
                    ),
                    308,
                );
            }
            // Signup-only marketing site: auth paths leave via the signup origin.
            if (isAuthPath(pathname) || pathname.startsWith("/dashboard")) {
                return NextResponse.redirect(
                    new URL(
                        signupOrigin(host, request.nextUrl.protocol),
                        request.url,
                    ),
                );
            }
            return NextResponse.next();
        }
        case "signup": {
            // Legacy /register URL: move callers to the /signup route so old
            // bookmarks and in-flight emails keep working.
            if (pathname === "/register" || pathname.startsWith("/register/")) {
                return NextResponse.redirect(
                    new URL(
                        pathname.replace(/^\/register/, "/signup"),
                        request.url,
                    ),
                    { status: 308 },
                );
            }
            if (isAuthPath(pathname) || isLegalPath(pathname)) {
                return NextResponse.next();
            }
            return NextResponse.redirect(new URL("/signup", request.url));
        }
        case "signin": {
            if (pathname === "/signin") {
                return NextResponse.rewrite(new URL("/login", request.url));
            }
            if (
                pathname === "/setup-mfa" ||
                pathname === "/mfa/verify" ||
                pathname === "/invite" ||
                isLegalPath(pathname)
            ) {
                return NextResponse.next();
            }
            return NextResponse.redirect(new URL("/signin", request.url));
        }
        case "docs": {
            // Auth paths leave via the signup origin (mirrors the marketing
            // surface) so the docs shell's "Create account" CTA keeps working
            // and no auth flow renders on the documentation hostname.
            if (isAuthPath(pathname) || pathname.startsWith("/dashboard")) {
                return NextResponse.redirect(
                    new URL(
                        signupOrigin(host, request.nextUrl.protocol),
                        request.url,
                    ),
                );
            }
            if (DOCS_ROOT_PASSTHROUGH.has(pathname)) {
                return NextResponse.next();
            }
            // Serve the internal /docs tree at the docs surface root without
            // exposing /docs in the browser URL. /docs-prefixed paths (docs
            // nav links and the Vercel fallback) map through unchanged so the
            // same links work on every surface.
            return NextResponse.rewrite(
                new URL(
                    `${docsInternalPath(pathname)}${request.nextUrl.search || ""}`,
                    request.url,
                ),
            );
        }
        case "workspace": {
            const isInternalWorkspaceRewrite =
                request.headers.get(INTERNAL_WORKSPACE_REWRITE_HEADER) === "1";

            if (isAuthPath(pathname)) {
                return NextResponse.redirect(
                    new URL(
                        signinOrigin(host, request.nextUrl.protocol, slug),
                        request.url,
                    ),
                );
            }

            // Every page on the workspace surface lives inside the authenticated
            // dashboard app, so a request without the session cookie has nothing
            // to render. Coarse presence check only - cookie validity is
            // enforced by the BFF on the next API call, and an invalid-but-
            // present cookie is handled by the client session restore. This
            // mirrors the former dashboard-layout check but keeps the whole
            // /dashboard tree statically prerenderable.
            if (!request.cookies.has(SESSION_COOKIE)) {
                return NextResponse.redirect(
                    new URL(
                        signinOrigin(
                            host,
                            request.nextUrl.protocol,
                            slug,
                            "Your session could not be established. Please sign in again.",
                        ),
                        request.url,
                    ),
                );
            }

            if (pathname === "/dashboard") {
                return NextResponse.redirect(
                    new URL(`/${request.nextUrl.search || ""}`, request.url),
                );
            }

            if (pathname === "/dashboard/invite") {
                // The workspace Invite page shares its name with the reserved auth
                // invite-accept route (/invite); keep it under /dashboard so the
                // normalize redirect below doesn't bounce it to the signin surface.
                return NextResponse.next();
            }

            if (
                pathname.startsWith("/dashboard/") &&
                !isInternalWorkspaceRewrite
            ) {
                return NextResponse.redirect(
                    new URL(
                        `${pathname.slice("/dashboard".length)}${request.nextUrl.search || ""}`,
                        request.url,
                    ),
                );
            }

            const internal =
                pathname === "/" ? "/dashboard" : `/dashboard${pathname}`;

            const headers = new Headers(request.headers);
            headers.set(INTERNAL_WORKSPACE_REWRITE_HEADER, "1");

            return NextResponse.rewrite(
                new URL(
                    `${internal}${request.nextUrl.search || ""}`,
                    request.url,
                ),
                {
                    request: {
                        headers,
                    },
                },
            );
        }
        default:
            return notFound();
    }
}

export const config = {
    // Skip Next-managed static assets and anything with a file extension.
    matcher: ["/((?!_next/static|_next/image|favicon.ico|.*\\..*).*)"],
};
