"""ai_guardian_reports - weekly integrity reports (SKY-90).

The Audit Guardian agent produces a weekly report summarizing audit log
activity across modules. Each report links to the flagged events it contains.
Reports are generated by a scheduled background job and reviewed by operators.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime

from sqlalchemy import (
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from ai_agent.models.base import Base


class AiGuardianReportModel(Base):
    """One weekly integrity report from the Audit Guardian."""

    __tablename__ = "ai_guardian_reports"
    __table_args__ = (
        CheckConstraint(
            "status IN ('generated', 'reviewed', 'archived')",
            name="ck_ai_guardian_reports_status",
        ),
        Index(
            "idx_guardian_reports_tenant_week",
            "tenant_id",
            "report_week_start",
        ),
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        primary_key=True,
        nullable=False,
    )
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, nullable=False
    )
    report_week_start: Mapped[date] = mapped_column(Date, nullable=False)
    report_week_end: Mapped[date] = mapped_column(Date, nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    total_events_scanned: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    flagged_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default=text("'generated'")
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
